function [results] = compare_procedure(procedures, info)
% COMPARE_PROCEDURE run different clustering procedures and obtain clustering
% quality statistics.
%
% RESULTS = COMPARE_PROCEDURE(PROCEDURES, INFO)
%
% This function provides a platform to run several clustering procedures and
% apply clustering statistics. The procedures to run are given as handles in a
% 1-dimensional cell array PROCEDURES. All procedures must take in only one
% input, which is the struct INFO (generated by initialize script). In other
% words, the signature of any procedure must be:
%
%   CLASS = ANY_PROCEDURE(INFO)
%
%   where CLASS is the classification vector for the spike data contained in
%   INFO.
%
% The results of the cluster quality evaluation
%
% INPUT:
% PROCEDURES    1-D cell array of procedure function handles
% INFO          Struct containing spike data and metadata
%
% OUTPUT:
% RESULTS       1-D cell array of the statistics results. 
%
% See also INITIALIZE


end