function nClusters = preview_clusters(spikes, feature, dim, defK)
% PREVIEW_CLUSTERS get user input of number of units from a preview of the spike
% feature space.
%
% NCLUSTERS = PREVIEW_CLUSTERS(SPIKES, FEATURE, DIM, DEFK)
%
% Plots the DIM-dimensional feature space of SPIKES as generated by FEATURE
% handle and asks user for the number of units in the plot.
%
% This function will be run in the context of an entire tank sorter, the user
% must give it a valid answer. It will not accept 'cancel' as valid input.
%
% Note that the feature space must have at least three dimensions. Any fewer
% will cause problems.
%
% The feature handle must have a signature of: @(spikes)

    if ~isa(feature, 'function_handle')
        error('Invalid feature handle');
    elseif dim ~= 2 && dim ~= 3
        error('Invalid dimension');
    end

    fs = feature(spikes);
    
    if size(fs, 2) < 3
        error('Feature space must be at least R3');
    end
    
    fs = fs(:, 1:3);
    
    figure('Name', 'preview');
    
    if dim == 2
        scatter(fs(:, 1), fs(:, 2), 0.9);
    else
        scatter3(fs(:, 1), fs(:, 2), fs(:, 3), 0.9);
    end
    
    prompt = {sprintf('Estimate of number of clusters')};
    numlines = 1;
    name = 'Estimate cluster count';
    def = {num2str(defK)};
    options.WindowStyle = 'normal';
    
    while true
        input = inputdlg(prompt, name, numlines, def, options);
        
        if isempty(input)
            continue
        end
        
        [nClusters, status] = str2num(input{1});
        if ~status || nClusters < 1 || ceil(nClusters) ~= floor(nClusters)
            continue;
        else
            close('preview');
            return
        end

    end
    
end